services:

    _defaults:
        autowire: true
        autoconfigure: true
        
    OSW3\TemplateTools\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Resources/'
    
    OSW3\TemplateTools\Twig\AppTwigExtension:
        tags: ['twig.extension']